spring:
  application.name: covid19
  datasource:
    url: jdbc:mysql://localhost:3306/covid19?createDatabaseIfNotExist=true
    username: root
    password: root

  data:
    mongodb:
      host: localhost
      port: 27017
      database: covid19


